name: "Pytest WF"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Pytest WF Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Hello World
        run: |
          echo "Hello World !"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Pip install
        run: pipenv install --dev
      - name: pytest
        continue-on-error: true
        run: pipenv run pytest --html=data/index.html
      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: data/**
      - name: Page upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: data
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
